<?php
/**
* Display help and module information
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/
function connect_help($path, $arg) {
  $output = '';  //declare your output variable
  switch ($path) {
    case "admin/help#onthisdate":
      $output = '<p>'.  t("Connects to non-default databases") .'</p>';
      break;
  }
  return $output;
} // function connect_help


/**
* Valid permissions for this module
* @return array An array of valid permissions for the onthisdate module
*/
function connect_perm() {
  return array('access connect');
} // function connect_perm()


/*
 * Accesses the database of your choice and extracts information from it
 */
function connect_block($op = 'list', $delta = 0, $edit = array()){
    if ($op == "list") {
        // Generate listing of blocks from this module, for the admin/block page
        $block = array();
        $block[0]["info"] = t('Connect to database');
        return $block;
    }

    else if ($op == 'view') {

        db_set_active('mydb');//Replace with the key you created for your database

        $result=db_query('SELECT * FROM test_table');//Replace with your query

        /*
         * Fetches the result from the query
         * Multiple rows can be fetched using loops
         * name and id should be replaced by columns in your database
         * More columns can be accessed as well
         */
        $row=db_fetch_object($result);
        $name=$row->name;
        $id=$row->id;
      
        $block_content = '';

        $block_content .=  $name .'<br />'.$id.'<br />';//This is what is going to be displayed in the block

        $block = array();
        $block['subject']="Connected to Database";//Replace with the subject of your choice
        $block['content']=$block_content;

        //Switches back to the default connection when finished.
        db_set_active('default');
        return $block;
  }

}




