<?php
/**
* Display help and module information
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/
function connect_help($path, $arg) {
  $output = '';  //declare your output variable
  switch ($path) {
    case "admin/help#onthisdate":
      $output = '<p>'.  t("Connects to non-default databases") .'</p>';
      break;
  }
  return $output;
} // function connect_help


/**
* Valid permissions for this module
* @return array An array of valid permissions for the onthisdate module
*/
function connect_perm() {
  return array('access connect');
} // function connect_perm()


function connect_block($op = 'list', $delta = 0, $edit = array()){
    if ($op == "list") {
        // Generate listing of blocks from this module, for the admin/block page
        $block = array();
        $block[0]["info"] = t('Connect to database');
        return $block;
    }

    else if ($op == 'view') {

        db_set_active('mydb');

        $result=db_query('SELECT * FROM test_table');

        $row=db_fetch_object($result);
        $name=$row->name;
        $id=$row->id;
        var_dump($row);

        $block_content = '';

        $block_content .=  $name .'<br />'.$id.'<br />';

        $block = array();
        $block['subject']="Connected to Database";
        $block['content']=$block_content;

        //Switch back to the default connection when finished.
        db_set_active('default');
        return $block;
  }

}




